import { Component } from '@angular/core';
import { NavController,Nav} from 'ionic-angular';

import { CardPage } from '../card/card';

@Component({
  selector: 'page-contact',
  templateUrl: 'contact.html'
})
export class ContactPage {

  chargers = [
    {
      "latitude": 75.162729,
      "longitude": 32.012078,
      "Dealer": "Hindustan Petroleum Corporation Ltd. - Raja Filling Station",
      "Address": "Dera Baba Nanak Road  Kalanour  Gurdaspur  Punjab   - myLPG.eu",
      "wall": 0,
      "j-1772": 3,
      "CHAdeMO": 3,
      "Tesla(roadster)": 0,
      "NEMA 14-50": 3,
      "Tesla": 1,
      "Type-2": 3,
      "Type-3": 1,
      "wall(BS1361)": 0,
      "Wall(euro)": 2,
      "Commando": 3,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 0,
      "CCS/SAE": 0,
      "THREEPhase": 0
    },
    {
      "latitude": 74.895569,
      "longitude": 31.642572,
      "Dealer": "Indian Oil Corporation Ltd. - Kanwar Filling Station",
      "Address": "Batala Road  Amritsar-143001   - myLPG.eu",
      "wall": 0,
      "j-1772": 0,
      "CHAdeMO": 1,
      "Tesla(roadster)": 1,
      "NEMA 14-50": 3,
      "Tesla": 3,
      "Type-2": 1,
      "Type-3": 4,
      "wall(BS1361)": 4,
      "Wall(euro)": 1,
      "Commando": 3,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 0,
      "CCS/SAE": 2,
      "THREEPhase": 2
    },
    {
      "latitude": 75.839524,
      "longitude": 31.498763,
      "Dealer": "Reliance Industries Ltd. - Reliance Industries Ltd. (ril)",
      "Address": "Nh-70 near Ms-32 vill Chak Gujran tehsil Hoshiarpur distt-hoshiarpur   - myLPG.eu",
      "wall": 4,
      "j-1772": 3,
      "CHAdeMO": 2,
      "Tesla(roadster)": 0,
      "NEMA 14-50": 4,
      "Tesla": 1,
      "Type-2": 2,
      "Type-3": 2,
      "wall(BS1361)": 3,
      "Wall(euro)": 0,
      "Commando": 4,
      "wall(AU/NZ)": 0,
      "Caravan Mains": 3,
      "CCS/SAE": 0,
      "THREEPhase": 2
    },
    {
      "latitude": 75.538349,
      "longitude": 31.337183,
      "Dealer": "Hindustan Petroleum Corporation Ltd. - Sas hp Gohira",
      "Address": "Jallandhar Nakodar Road  Gohira  Jallandhar  Punjab   - myLPG.eu",
      "wall": 2,
      "j-1772": 0,
      "CHAdeMO": 4,
      "Tesla(roadster)": 4,
      "NEMA 14-50": 0,
      "Tesla": 1,
      "Type-2": 1,
      "Type-3": 1,
      "wall(BS1361)": 0,
      "Wall(euro)": 0,
      "Commando": 4,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 0,
      "CCS/SAE": 1,
      "THREEPhase": 4
    },
    {
      "latitude": 75.569544,
      "longitude": 31.322422,
      "Dealer": "Indian Oil Corporation Ltd. - Amar Highways",
      "Address": "G.t.road  (ludhiana-jalandar)  Plot No. 225/5  Pin-144 010   - myLPG.eu",
      "wall": 4,
      "j-1772": 2,
      "CHAdeMO": 2,
      "Tesla(roadster)": 0,
      "NEMA 14-50": 2,
      "Tesla": 1,
      "Type-2": 3,
      "Type-3": 3,
      "wall(BS1361)": 3,
      "Wall(euro)": 1,
      "Commando": 4,
      "wall(AU/NZ)": 0,
      "Caravan Mains": 0,
      "CCS/SAE": 1,
      "THREEPhase": 2
    },
    {
      "latitude": 75.863883,
      "longitude": 30.901249,
      "Dealer": "Hindustan Petroleum Corporation Ltd. - Pathak Power Point",
      "Address": "m Mundiya Kalan  Ludhiana   - myLPG.eu",
      "wall": 2,
      "j-1772": 4,
      "CHAdeMO": 4,
      "Tesla(roadster)": 3,
      "NEMA 14-50": 0,
      "Tesla": 1,
      "Type-2": 0,
      "Type-3": 3,
      "wall(BS1361)": 3,
      "Wall(euro)": 2,
      "Commando": 2,
      "wall(AU/NZ)": 1,
      "Caravan Mains": 3,
      "CCS/SAE": 3,
      "THREEPhase": 3
    },
    {
      "latitude": 75.795373,
      "longitude": 30.889484,
      "Dealer": "Indian Oil Corporation Ltd. - Laxmi S/stn.",
      "Address": "Ferozepur Road  Ludhiana   - myLPG.eu",
      "wall": 1,
      "j-1772": 2,
      "CHAdeMO": 2,
      "Tesla(roadster)": 2,
      "NEMA 14-50": 4,
      "Tesla": 4,
      "Type-2": 3,
      "Type-3": 3,
      "wall(BS1361)": 2,
      "Wall(euro)": 3,
      "Commando": 1,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 1,
      "CCS/SAE": 2,
      "THREEPhase": 1
    },
    {
      "latitude": 76.765385,
      "longitude": 30.728953,
      "Dealer": "Bharat Petroleum Corporation Ltd. - Eem Pee Motors",
      "Address": "Sector- 22   Chandigarh   - myLPG.eu",
      "wall": 4,
      "j-1772": 2,
      "CHAdeMO": 0,
      "Tesla(roadster)": 1,
      "NEMA 14-50": 2,
      "Tesla": 1,
      "Type-2": 0,
      "Type-3": 0,
      "wall(BS1361)": 4,
      "Wall(euro)": 4,
      "Commando": 1,
      "wall(AU/NZ)": 1,
      "Caravan Mains": 1,
      "CCS/SAE": 3,
      "THREEPhase": 2
    },
    {
      "latitude": 76.77089,
      "longitude": 30.724168,
      "Dealer": "Indian Oil Corporation Ltd. - M/s.allied S/stn.",
      "Address": "Sector 34-b  Chandigarh   - myLPG.eu",
      "wall": 1,
      "j-1772": 3,
      "CHAdeMO": 2,
      "Tesla(roadster)": 1,
      "NEMA 14-50": 4,
      "Tesla": 0,
      "Type-2": 0,
      "Type-3": 2,
      "wall(BS1361)": 1,
      "Wall(euro)": 3,
      "Commando": 0,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 4,
      "CCS/SAE": 4,
      "THREEPhase": 4
    },
    {
      "latitude": 76.748925,
      "longitude": 30.709685,
      "Dealer": "Indian Oil Petrol Pump + CNG Station",
      "Address": "Sector 44C 160047 Chandigarh - myLPG.eu",
      "wall": 3,
      "j-1772": 2,
      "CHAdeMO": 0,
      "Tesla(roadster)": 3,
      "NEMA 14-50": 4,
      "Tesla": 3,
      "Type-2": 4,
      "Type-3": 0,
      "wall(BS1361)": 1,
      "Wall(euro)": 1,
      "Commando": 2,
      "wall(AU/NZ)": 4,
      "Caravan Mains": 1,
      "CCS/SAE": 2,
      "THREEPhase": 3
    },
    {
      "latitude": 76.403392,
      "longitude": 30.562832,
      "Dealer": "Indian Oil Corporation Ltd. - Hemkunt Service Station",
      "Address": "Sirhind Road   - myLPG.eu",
      "wall": 3,
      "j-1772": 3,
      "CHAdeMO": 1,
      "Tesla(roadster)": 4,
      "NEMA 14-50": 3,
      "Tesla": 1,
      "Type-2": 2,
      "Type-3": 1,
      "wall(BS1361)": 0,
      "Wall(euro)": 0,
      "Commando": 2,
      "wall(AU/NZ)": 0,
      "Caravan Mains": 2,
      "CCS/SAE": 3,
      "THREEPhase": 1
    },
    {
      "latitude": 78.003912,
      "longitude": 30.332848,
      "Dealer": "Indian Oil Corporation Ltd. - Ashirwad Filling Station",
      "Address": "Ballupur  Chakrata Road  Dehradun- 248 001   - myLPG.eu",
      "wall": 4,
      "j-1772": 3,
      "CHAdeMO": 3,
      "Tesla(roadster)": 3,
      "NEMA 14-50": 4,
      "Tesla": 0,
      "Type-2": 1,
      "Type-3": 4,
      "wall(BS1361)": 4,
      "Wall(euro)": 2,
      "Commando": 4,
      "wall(AU/NZ)": 1,
      "Caravan Mains": 4,
      "CCS/SAE": 0,
      "THREEPhase": 1
    },
    {
      "latitude": 77.301108,
      "longitude": 30.290986,
      "Dealer": "Vanaz Engineers Ltd. - Maa Sharada Auto LPG Pump.",
      "Address": "at Post Parsada  Raipur-bilaspur Road  Bilaspur.   - myLPG.eu",
      "wall": 4,
      "j-1772": 0,
      "CHAdeMO": 0,
      "Tesla(roadster)": 0,
      "NEMA 14-50": 0,
      "Tesla": 3,
      "Type-2": 2,
      "Type-3": 3,
      "wall(BS1361)": 0,
      "Wall(euro)": 0,
      "Commando": 2,
      "wall(AU/NZ)": 0,
      "Caravan Mains": 3,
      "CCS/SAE": 2,
      "THREEPhase": 2
    },
    {
      "latitude": 78.149354,
      "longitude": 30.166599,
      "Dealer": "Indian Oil Corporation Ltd. - Shaheed Chandrawat",
      "Address": "Majri Mafi  Dehradun   - myLPG.eu",
      "wall": 4,
      "j-1772": 4,
      "CHAdeMO": 0,
      "Tesla(roadster)": 4,
      "NEMA 14-50": 0,
      "Tesla": 2,
      "Type-2": 3,
      "Type-3": 0,
      "wall(BS1361)": 1,
      "Wall(euro)": 2,
      "Commando": 3,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 4,
      "CCS/SAE": 1,
      "THREEPhase": 3
    },
    {
      "latitude": 78.784643,
      "longitude": 30.132249,
      "Dealer": "Aegis Logistics Ltd. - Mansha Agency",
      "Address": "Plot No. 53  Panvel Co-op. Industrial Estate Ltd.  Old Bombay- Pune Road  Tal. Panvel  Dist. Raigad-410 206   - myLPG.eu",
      "wall": 1,
      "j-1772": 0,
      "CHAdeMO": 0,
      "Tesla(roadster)": 2,
      "NEMA 14-50": 3,
      "Tesla": 3,
      "Type-2": 0,
      "Type-3": 0,
      "wall(BS1361)": 1,
      "Wall(euro)": 3,
      "Commando": 1,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 3,
      "CCS/SAE": 4,
      "THREEPhase": 3
    },
    {
      "latitude": 77.55274,
      "longitude": 29.962583,
      "Dealer": "Indian Oil Corporation Ltd. - Deepshikha Service Station",
      "Address": "3/1328/66  Civil Lines  Bajoria Marg (pin 247001)   - myLPG.eu",
      "wall": 1,
      "j-1772": 0,
      "CHAdeMO": 0,
      "Tesla(roadster)": 0,
      "NEMA 14-50": 4,
      "Tesla": 4,
      "Type-2": 1,
      "Type-3": 4,
      "wall(BS1361)": 3,
      "Wall(euro)": 3,
      "Commando": 4,
      "wall(AU/NZ)": 4,
      "Caravan Mains": 0,
      "CCS/SAE": 3,
      "THREEPhase": 1
    },
    {
      "latitude": 78.005393,
      "longitude": 29.945663,
      "Dealer": "Indian Oil Corporation Ltd. - Amol Filling Station",
      "Address": "Chutmalpur-dehradun Rd  Amanat Garh  Distt Hardwar   - myLPG.eu",
      "wall": 2,
      "j-1772": 1,
      "CHAdeMO": 0,
      "Tesla(roadster)": 1,
      "NEMA 14-50": 1,
      "Tesla": 3,
      "Type-2": 1,
      "Type-3": 2,
      "wall(BS1361)": 1,
      "Wall(euro)": 0,
      "Commando": 4,
      "wall(AU/NZ)": 2,
      "Caravan Mains": 2,
      "CCS/SAE": 3,
      "THREEPhase": 0
    },
    {
      "latitude": 78.163819,
      "longitude": 29.945155,
      "Dealer": "Indian Oil Corporation Ltd. - Aastha Filling Station",
      "Address": "Shatranshah  Roorkee Road  Hardwar   - myLPG.eu",
      "wall": 2,
      "j-1772": 1,
      "CHAdeMO": 4,
      "Tesla(roadster)": 2,
      "NEMA 14-50": 2,
      "Tesla": 1,
      "Type-2": 1,
      "Type-3": 2,
      "wall(BS1361)": 3,
      "Wall(euro)": 1,
      "Commando": 4,
      "wall(AU/NZ)": 1,
      "Caravan Mains": 4,
      "CCS/SAE": 3,
      "THREEPhase": 0
    }]

  constructor() {
  }


}
